const express = require ("express");
require("dotenv").config();
const app = express();
const port = process.env.PORT;
const cors = require ("cors");
require ("./config/mongoose.config");
app.use(express.json(), express.urlencoded({ extended: true }), cors());
const AllMyProductRoutes = require("./routes/product.routes");
AllMyProductRoutes(app);
app.listen(port, () => console.log(`Listening on port: ${port}`) );
